/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProductProductIdNewRouteImport } from './routes/product.$productId-new'
import { Route as ProductProductIdInteractiveRouteImport } from './routes/product.$productId-interactive'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'

const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdNewRoute = ProductProductIdNewRouteImport.update({
  id: '/product/$productId-new',
  path: '/product/$productId-new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdInteractiveRoute =
  ProductProductIdInteractiveRouteImport.update({
    id: '/product/$productId-interactive',
    path: '/product/$productId-interactive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/$productId-interactive': typeof ProductProductIdInteractiveRoute
  '/product/$productId-new': typeof ProductProductIdNewRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/$productId-interactive': typeof ProductProductIdInteractiveRoute
  '/product/$productId-new': typeof ProductProductIdNewRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/$productId-interactive': typeof ProductProductIdInteractiveRoute
  '/product/$productId-new': typeof ProductProductIdNewRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmation'
    | '/payment-success'
    | '/checkout/$productId'
    | '/product/$productId'
    | '/product/$productId-interactive'
    | '/product/$productId-new'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmation'
    | '/payment-success'
    | '/checkout/$productId'
    | '/product/$productId'
    | '/product/$productId-interactive'
    | '/product/$productId-new'
    | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/confirmation'
    | '/payment-success'
    | '/checkout/$productId'
    | '/product/$productId'
    | '/product/$productId-interactive'
    | '/product/$productId-new'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmationRoute: typeof ConfirmationRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ProductProductIdInteractiveRoute: typeof ProductProductIdInteractiveRoute
  ProductProductIdNewRoute: typeof ProductProductIdNewRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId-new': {
      id: '/product/$productId-new'
      path: '/product/$productId-new'
      fullPath: '/product/$productId-new'
      preLoaderRoute: typeof ProductProductIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId-interactive': {
      id: '/product/$productId-interactive'
      path: '/product/$productId-interactive'
      fullPath: '/product/$productId-interactive'
      preLoaderRoute: typeof ProductProductIdInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmationRoute: ConfirmationRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ProductProductIdInteractiveRoute: ProductProductIdInteractiveRoute,
  ProductProductIdNewRoute: ProductProductIdNewRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
